engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
  - client/src/**
exclude_paths:
- "client/dist/**"
