engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - client/src/**
exclude_paths:
- "client/dist/**"
