---
engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: PSR1,PSR2
  csslint:
    enabled: true
    
ratings:
  paths:
  - "**.js"
  - "**.php"
  - "**.css"

exclude_paths: 
