---
Name: assetadmin
---
SilverStripe\CMS\Controllers\AssetAdmin:
  url_segment: 'old-assets'
SilverStripe\Assets\File:
  extensions:
    - 'SilverStripe\AssetAdmin\Controller\AssetAdminFile'
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\AssetAdmin\Controller\AssetAdminFieldsExtension
